language: python
python:
  - '3.8'

dist: bionic

sudo: false

cache: false

addons:
  apt:
    packages:
    - cppcheck
    - binutils

install:
  - pip install -U platformio sphinx recommonmark sphinx_bootstrap_theme
  - pip install -r requirements.txt
  - platformio update
  - cd patches; ./check_puya_patch; cd ..

env:
  - ENV=custom_ESP32_4M316k
  - ENV=custom_ESP32_4M316k_ETH
  #- ENV=custom_ESP8266_1M
  - ENV=custom_ESP8266_4M1M
  #- ENV=custom_ESP8266_4M2M
  #- ENV=custom_ESP8266_4M2M_LittleFS
  #- ENV=custom_alt_wifi_ESP8266_1M
  - ENV=custom_alt_wifi_ESP8266_4M1M
  #- ENV=custom_beta_ESP8266_1M
  #- ENV=custom_beta_ESP8266_4M1M
  - ENV=custom_sdk3_ESP8266_4M1M
  - ENV=dev_ESP8266_4M1M
  - ENV=hard_SONOFF_POW_4M1M
  - ENV=hard_Shelly_1_2M256
  - ENV=hard_Shelly_PLUG_S_2M256
  - ENV=hard_Ventus_W266
  - ENV=hard_LCtech_relay_x2_1M
  - ENV=hard_other_POW_ESP8285_1M
  - ENV=minimal_IRext_ESP8266_1M
  - ENV=minimal_IRext_ESP8266_4M1M
  - ENV=minimal_IRext_ESP8266_4M2M
  #- ENV=minimal_core_242_ESP8266_1M_OTA
  #- ENV=minimal_core_242_ESP8285_1M_OTA
  - ENV=minimal_core_274_ESP8266_1M_OTA_Domoticz
  - ENV=minimal_core_274_ESP8266_1M_OTA_FHEM_HA
  - ENV=minimal_core_274_ESP8285_1M_OTA_Domoticz
  - ENV=minimal_core_274_ESP8285_1M_OTA_FHEM_HA
  #- ENV=minimal_core_274_sdk3_ESP8266_1M_OTA_Domoticz
  #- ENV=minimal_core_274_sdk3_ESP8266_1M_OTA_FHEM_HA
  #- ENV=minimal_core_274_sdk3_ESP8285_1M_OTA_Domoticz
  #- ENV=minimal_core_274_sdk3_ESP8285_1M_OTA_FHEM_HA
  #- ENV=normal_ESP8266_16M_LittleFS
  - ENV=normal_ESP8266_1M
  - ENV=normal_ESP8266_1M_VCC
  - ENV=normal_ESP8266_4M1M
  - ENV=normal_ESP8266_4M1M_VCC
  - ENV=normal_ESP8285_1M
  - ENV=normal_IRext_no_rx_ESP8266_4M2M
  - ENV=normal_WROOM02_2M256
  - ENV=normal_WROOM02_2M
  - ENV=normal_alt_wifi_ESP8266_1M
  - ENV=normal_alt_wifi_ESP8266_1M_VCC
  - ENV=normal_alt_wifi_ESP8266_4M1M
  #- ENV=normal_sdk3_ESP8266_1M
  #- ENV=spec_debug_beta_custom_ESP8266_4M1M
  #- ENV=spec_debug_custom_ESP32_4M316k
  #- ENV=spec_debug_custom_ESP8266_4M1M
  #- ENV=spec_memanalyze_ESP8266
  - ENV=test_ESP32-wrover-kit_4M316k
  - ENV=test_ESP32-wrover-kit_4M316k_ETH
  - ENV=test_ESP32_4M316k
  - ENV=test_ESP32_4M316k_ETH
  - ENV=test_ESP32_4M316k_lolin_d32_pro
  - ENV=test_ESP8266_4M1M_VCC
  #- ENV=test_ESP8266_4M1M_VCC_MDNS_SD
  #- ENV=test_alt_wifi_ESP8266_4M1M_VCC
  #- ENV=test_beta_ESP8266_16M_LittleFS
  - ENV=test_beta_ESP8266_4M1M

script:
  - PLATFORMIO_BUILD_FLAGS="-D CONTINUOUS_INTEGRATION" platformio run -e $ENV

before_deploy:
  - ./before_deploy

deploy:
  provider: releases
  prerelease: true
  api_key:
    secure: bZeuKI7evXeZYmGayfcvIC1fThBGcksAyOrCbZ8kAGeTbHGJqFLBBy8to5UpNBSZVfeDWo25Iqy8Pfbyb7p2c1hg6fG9jS0UzQkLnoUNMxpUM1dJACkZxvFdP4Br3Y3vUPWtrWUbo8rN/b3E6tjSNLE7vQiwsarj+eWTO2V6BGcsN0eHc04/UCM2+DcHvJ4y7Ec36yIUaClNAWMal1osBYaViruylOdBKT/WDs1ZMoJMceXCfxMQ/8J2moYvymKfSkXSmoMGmzlTuq8v5N4AweutjpC4Zba2BbxIJv+PwWjhfIgTviHFggSU90UPTKVWYv13vms92VVKz1CDVrUQNn+YQes9+ROPUnrMc9bJ+q7E1lWJRZeDMqGECB+8BjUtUk6H81K+XhOnW1mtZiMnvMCwkmE0OT1eBObGMcpR962/DUBoQDmulMs2IieB0dLobmUBhpc1syrKEPKxjY7yhhQMr6In82jODVLR3qDkNQ8xtIfevzCo/ocUjiOrXW4b/pDMy28Yh109DMb/KSWEsjjkkpXhsT1YVy2MwOa7FRhHFW+SNKX4Us8T75H+pO4mQ4afnPEtjYKodj7XD92zqNxKfMx3elEx5RK6HKekHjpXdYtuXzGONB9StA+2T43/2llt3n5fzv4BRfCumBEJ77/ufB0U/uhsCe6lVwJf34U=
  file_glob: true
  file: ESPEasy*.zip

  skip_cleanup: true
  on:
      tags: true
    # repo: psy0rz/ESPEasy-platformio

notifications:
  email: false
